
[phases.setup]
packages = ["postgresql"]


[phases.install]
commands = [
  "python -m pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
start = "uvicorn main:app --reload --host 0.0.0.0 --port 8080"
